### ISSUE TITLE
Request for a relatively simple UI improvement.

### ISSUE THREAD

**Issue by Anadian** [stxapps/brace-client#113]
I've been using brace.to for about two years, and I have a relatively simple suggestion to improve usability.
![image](https://github.com/user-attachments/assets/351a4dff-7fde-4d99-bb30-eb928bcdfc69)
This is how it's always looked when changing the viewed list in the web UI. You click a button to open a tiny popup (that doesn't even use half of the available space) to scroll down a list to click the one you wish to change to. It seems to me there's no reason why this couldn't be significantly improved, at least in a desktop view, by having the list selection be a whole column on the left of all the main content; it can be always-visible or, if you wish, have button toggle it between hidden and visible. Now, in the meantime, if that's too much of a UX overall, you could rather easily change the height of the popup to use a lot more of the available screen real estate and at least reduce the scrolling required to get to the desired list. I [even](https://github.com/stxapps/brace-client/blob/b52d6ca97582697e2bc912acb1011f5b8ec0a83e/packages/web/src/components/ListNamesPopup.js#L247) [darted](https://github.com/stxapps/brace-client/blob/master/packages/web/src/components/index.js#L55) [through](https://github.com/stxapps/brace-client/blob/master/packages/web/src/selectors/index.js#L204) [the](https://github.com/stxapps/brace-client/blob/master/packages/web/src/utils/index.js#L488) [code](https://github.com/stxapps/brace-client/blob/master/packages/web/src/components/ListPanel.js) myself to see if I could isolate the line that's the culprit in having the popup take up such a needlessly-small region of the screen.

Also, when I cloned the repo, in an attempt to see if I could fix it myself as a pull request, I encountered an issue after installing the dependencies and attempting to run the build script specified in the `package.json`:
 ```bash
> brace-client-web@0.37.0 build /home/<username>/dev/brace-client/packages/web
> yarn run patch-js && yarn run build-js && yarn run copy-hard-coding

yarn run v1.22.22
$ node bin/patch.js
node:fs:455
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 'node_modules/@stacks/network/dist/fetch.js'
    at Object.readFileSync (node:fs:455:20)
    at replaceMatchedLine (/home/<username>/dev/brace-client/packages/web/bin/patch.js:4:19)
    at patchFetch (/home/<username>/dev/brace-client/packages/web/bin/patch.js:29:3)
    at Object.<anonymous> (/home/<username>/dev/brace-client/packages/web/bin/patch.js:87:1)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/@stacks/network/dist/fetch.js'
}

Node.js v21.7.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ELIFECYCLE  Command failed with exit code 1.
```
Surely enough, there is no `@stacks/network` package in `node_modules` let alone the specific file referenced. Possibly, an internal development package missing from `package.json`? The `auth`, `connect`, `encryption`, `storage`, and `wallet-sdk` packages specified in `package.json` are all present and accounted for in `node_modules`.

**Comment by Anadian** [comment]
Regarding the build issues:
Attempting to add `@stacks/network@6.16.1' had it tell me that `No matching version found for @stacks/network@6.16.1`. Looking at `@stacks/storage/package.json` it specifies "^6.17.0" as the dependent version. Simply trying `add @stacks/network@6` seemed to work. It now completes the `patch-js` but then fails in the middle build script:
```
> brace-client-web@0.37.0 build /home/<username>/dev/brace-client/packages/web
> yarn run patch-js && yarn run build-js && yarn run copy-hard-coding

yarn run v1.22.22
$ node bin/patch.js
Done in 0.08s.
yarn run v1.22.22
$ react-app-rewired build
Creating an optimized production build...

warn - As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
warn - Remove it from the `plugins` array in your configuration to eliminate this warning.
Failed to compile.

Module not found: Error: Can't resolve 'redux-persist/constants' in '/home/<username>/dev/brace-client/packages/web/src/reducers'


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ELIFECYCLE  Command failed with exit code 1.
[<userinfo>:web]bash$ ls /home/<username>/dev/brace-client/packages/web/src/reducers
cachedFPathsReducer.js        displayReducer.js      iapReducer.js     infoReducer.js        listNameEditorsReducer.js  lockSettingsReducer.js  pendingTagsReducer.js  stacksAccessReducer.js    timePickReducer.js
conflictedSettingsReducer.js  fetchedMoreReducer.js  imagesReducer.js  linkEditorReducer.js  localSettingsReducer.js    pendingPinsReducer.js   settingsReducer.js     tagEditorReducer.js       userReducer.js
customEditorReducer.js        fetchedReducer.js      index.js          linksReducer.js       lockEditorReducer.js       pendingSsltsReducer.js  snapshotReducer.js     tagNameEditorsReducer.js  windowReducer.js
```
I've included a `ls` of the directory it specifies; no clue what it's looking for though.

Regarding the UX suggestions:
"Do you think how high it should be? How many lists should be shown before scrolling? The current value is 5 lists. We can increase it."
Well, I think the space between the start of popup and the top of the page is reasonable but could still be contracted a bit and clearly there's a lot more vertical space that should be utilised. As for how many lists should be shown before it starts scrolling, that's a question that seems a little backward from a form/function perspective: really you should specify an area, I'd say at least 80% of the vertical and 30% of the horizontal area of the page, and it should try and fit as many lists in that area, without going under a readable font point size, and add the scroll bars as necessary. So I guess my answer would be: "as many as possible to best utilise the screen space." While I've got plenty of experience with Javascript and NodeJS, I admittedly have very minimal experience with React and Tailwind so I'm not sure how precisely you'd accomplish this using those frameworks but, just from a pure HTML/CSS point, it should be easy.

**Comment by stxapps** [comment]
We got it. We'll start working on it now. It should be done in days. 🤝

**Comment by Anadian** [comment]
Great stuff! 
![Screenshot_20241217_200105](https://github.com/user-attachments/assets/dfbffe79-e0ba-499a-a68f-54463a8ad4eb)

Still consider the side bar option but this is a great improvement.
