### ISSUE TITLE
Bug/Enhancement: require confirmation prior to initial cleanup

### ISSUE THREAD

**Issue by slightly-random** [stxapps/brace-client#61]
I noticed an indication of cleanup after upgrading my client, and not knowing what that might mean I found Settings >> Misc >> Auto Cleanup which was enabled by default.

I dislike the idea that links were removed and wonder how many and what they were.

**Comment by stxapps** [comment]
By default, links in the Trash are removed permanently after 45 days. You can disable it at Settings -> Misc. -> Auto Cleanup.

We clean up only links already removed by the user and in the Trash for 45 days. We believe it's a standard procedure like in Google Drive and Apple Photos.

Is cleanup the wrong word? Is the message not clear? Or no need to display it at the top?

P.S. Thank you for letting us know your thought. We appreciate.

**Comment by stxapps** [comment]
We'll close this issue for now. Please feel free to reopen it if you have any questions.
